import io

import pandas as pd
import pytest

from sif_scorecard.ingest import (
    IngestError,
    classify_table,
    detect_header_row,
    detect_pii_columns,
    profile_table,
    read_table,
    suggest_column,
)


def _csv(text: str, name: str = "upload.csv") -> io.BytesIO:
    buf = io.BytesIO(text.encode("utf-8"))
    buf.name = name
    return buf


# --- header detection -----------------------------------------------------


def test_detects_header_under_export_preamble():
    # The shape every report-builder export has: title, blurb, blank, header.
    raw = pd.DataFrame(
        [
            ["Incident Reports ALL INFO", None, None],
            ["Build your own report template.", None, None],
            [None, None, None],
            ["Event Title", "Type", "Classification"],
            ["Cut - CL", "Incident", "First Aid"],
        ]
    )
    assert detect_header_row(raw) == 3


def test_detects_header_on_first_row_when_clean():
    raw = pd.DataFrame(
        [["Hazard", "Controls"], ["Fall from roof", "harness"]]
    )
    assert detect_header_row(raw) == 0


def test_read_table_uses_detected_header():
    df = read_table(
        _csv(
            "My Export\n"
            "generated by system\n"
            "Hazard,Controls\n"
            "Fall from 20 ft roof,warning line\n"
            "480V panel work,LOTO\n"
        )
    )
    assert list(df.columns) == ["Hazard", "Controls"]
    assert len(df) == 2


def test_read_table_survives_non_utf8_bytes():
    buf = io.BytesIO("Hazard,Controls\nMolten salt bath 65\xb0C,fume hood\n".encode("latin-1"))
    buf.name = "legacy.csv"
    df = read_table(buf)
    assert len(df) == 1


def test_read_table_deduplicates_column_labels():
    df = read_table(_csv("Hazard,Hazard,Controls\na,b,c\n"))
    assert len(set(df.columns)) == 3


def test_read_table_rejects_empty_file():
    with pytest.raises(IngestError, match="empty"):
        read_table(_csv("\n"))


# --- privacy --------------------------------------------------------------


def test_flags_pii_columns_by_name():
    df = pd.DataFrame(
        {
            "Hazard": ["fall"],
            "First Name": ["Ada"],
            "Reported By": ["B. Chen"],
            "Employee ID": ["E-9"],
            "Location": ["Roof"],
        }
    )
    flagged = detect_pii_columns(df)
    assert set(flagged) == {"First Name", "Reported By", "Employee ID"}
    assert "Hazard" not in flagged and "Location" not in flagged


def test_does_not_flag_names_of_things_as_personal_data():
    df = pd.DataFrame(
        {
            "Site Name": ["Santa Rosa"],
            "Equipment Name": ["Press 3"],
            "Task Name": ["Die change"],
            "Employee Name": ["Ada L"],
        }
    )
    flagged = detect_pii_columns(df)
    assert flagged == ["Employee Name"]


def test_normalizes_multiline_column_labels():
    df = read_table(_csv('"Site Name\n(free text)",Hazard\nSanta Rosa,fall\n'))
    assert "Site Name (free text)" in df.columns


def test_flags_pii_by_email_shaped_values():
    df = pd.DataFrame(
        {"Hazard": ["fall"] * 3, "Contact Info": ["a@b.com", "c@d.org", "e@f.net"]}
    )
    assert "Contact Info" in detect_pii_columns(df)


def test_profile_reports_shape_and_pii():
    df = read_table(_csv("Hazard,Employee Name\nfall from roof,Ada L\n"))
    profile = profile_table(df, name="Sheet1")
    assert profile.n_rows == 1
    assert profile.columns == ["Hazard", "Employee Name"]
    assert profile.pii_columns == ["Employee Name"]


# --- mapping suggestions --------------------------------------------------


def test_suggests_columns_for_roles():
    cols = ["Task", "Hazard / Concern", "Existing Controls", "Work Area",
            "Frequency", "# Exposed", "Last Audit Result"]
    assert suggest_column(cols, "description") == "Task"
    assert suggest_column(cols, "controls") == "Existing Controls"
    assert suggest_column(cols, "location") == "Work Area"
    assert suggest_column(cols, "frequency") == "Frequency"
    assert suggest_column(cols, "workers") == "# Exposed"


def test_suggest_returns_none_when_no_match():
    assert suggest_column(["alpha", "beta"], "controls") is None


# --- end-to-end classification of an arbitrary table ----------------------


def test_classify_table_produces_reviewable_rows():
    df = pd.DataFrame(
        {
            "Hazard": [
                "Work near roof edge, approx 20 ft",
                "Racking breakers in 480V MCC room",
                "Repetitive lifting of cases",
            ],
            "Existing Controls": [
                "Warning line 6 ft from edge; buddy system",
                "LOTO EP-201, arc flash suit",
                "Lift training",
            ],
            "Frequency": ["monthly", "monthly", "daily"],
            "# Exposed": [2, 3, 10],
        }
    )
    review = classify_table(
        df, "Hazard", controls_col="Existing Controls",
        frequency_col="Frequency", workers_col="# Exposed",
    )
    assert len(review) == 3
    roof, panel, lifting = review.iloc[0], review.iloc[1], review.iloc[2]

    assert roof["high_energy"] == "yes" and not roof["direct_control"]
    assert "warning" in roof["control_type"]  # named, not credited
    assert panel["high_energy"] == "yes" and panel["direct_control"]
    assert lifting["high_energy"] == "no"
    # Every row explains itself.
    assert all(review["why_energy"].str.len() > 0)
    assert all(review["why_control"].str.len() > 0)


def test_classify_table_skips_blank_descriptions():
    df = pd.DataFrame({"Hazard": ["fall from roof", "", None]})
    assert len(classify_table(df, "Hazard")) == 1


def test_classify_table_errors_when_column_all_blank():
    df = pd.DataFrame({"Hazard": ["", None], "Other": ["a", "b"]})
    with pytest.raises(IngestError, match="hazard description"):
        classify_table(df, "Hazard")


def test_classify_table_errors_on_missing_column():
    with pytest.raises(IngestError, match="not in the file"):
        classify_table(pd.DataFrame({"a": [1]}), "Nope")
